name: Quality Assurance GitHub Actions Workflow

on:
  pull_request:
    branches: [development]

jobs:

  cache-dependencies:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up .npmrc
        run: | 
          echo "registry=http://${{ secrets.VERDACCIO_REGISTRY }}/" > .npmrc
          echo "//${{ secrets.VERDACCIO_REGISTRY }}/:_authToken=\"${{ secrets.VERDACCIO_TOKEN }}\"" >> .npmrc
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install

  test:
    runs-on: ubuntu-latest
    environment: Dev
    needs: cache-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up .npmrc
        run: | 
          echo "registry=http://${{ secrets.VERDACCIO_REGISTRY }}/" > .npmrc
          echo "//${{ secrets.VERDACCIO_REGISTRY }}/:_authToken=\"${{ secrets.VERDACCIO_TOKEN }}\"" >> .npmrc
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: npm install --if-present
      - run: npm run test 

  lint:
    runs-on: ubuntu-latest
    environment: Dev
    needs: cache-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up .npmrc
        run: | 
          echo "registry=http://${{ secrets.VERDACCIO_REGISTRY }}/" > .npmrc
          echo "//${{ secrets.VERDACCIO_REGISTRY }}/:_authToken=\"${{ secrets.VERDACCIO_TOKEN }}\"" >> .npmrc
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm install --if-present
      - run: npm run lint

  coverage:
    runs-on: ubuntu-latest
    environment: Dev
    needs: cache-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up .npmrc
        run: | 
          echo "registry=http://${{ secrets.VERDACCIO_REGISTRY }}/" > .npmrc
          echo "//${{ secrets.VERDACCIO_REGISTRY }}/:_authToken=\"${{ secrets.VERDACCIO_TOKEN }}\"" >> .npmrc
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: npm install --if-present
      - run: npm run coverage
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          github-token: ${{ secrets.GH_PAT }}
          lcov-file: ./coverage/lcov.info
          delete-old-comments: true

  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check Title Format
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(feat|fix|refactor|docs|test):\s\[\w+-\d+\]\s.+$'
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
  security-check:
    runs-on: ubuntu-latest
    environment: Dev
    needs: cache-dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Set up .npmrc
        run: | 
          echo "registry=http://${{ secrets.VERDACCIO_REGISTRY }}/" > .npmrc
          echo "//${{ secrets.VERDACCIO_REGISTRY }}/:_authToken=\"${{ secrets.VERDACCIO_TOKEN }}\"" >> .npmrc
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: npm install --if-present
      - run: npm audit --audit-level=high
        continue-on-error: true
