name: Quality Assurance GitHub Actions Workflow

on:
  pull_request:
    branches: [development]

jobs:

  test:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: npm install
      - run: npm run test 


 