name: Quality Assurance GitHub Actions Workflow

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "run tests"
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm install
      - run: npm run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "run linter"
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm install
      - run: npm run lint

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm install
      - run: npm run coverage
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          github-token: ${{ secrets.GH_PAT }}
          lcov-file: ./coverage/lcov.info
          delete-old-comments: true

  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check Title Format
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(feat|fix|refactor|docs|test):\s\[\w+-\d+\]\s.+$'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run npm audit
        run: npm audit --audit-level=high
        continue-on-error: true