name: Quality Assurance GitHub Actions Workflow

on:
  pull_request:
    branches: [development]

jobs:

  test:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up .npmrc
        run: | 
          echo "registry=http://${{ secrets.VERDACCIO_REGISTRY }}/" > .npmrc
          echo "//${{ secrets.VERDACCIO_REGISTRY }}/:_authToken=\"${{ secrets.VERDACCIO_TOKEN }}\"" >> .npmrc
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: npm install
      - run: npm run test 


